# Generated by Django 2.2.4 on 2020-04-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='companyName',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='email',
            field=models.EmailField(default='you default value or example@email.com', max_length=253),
        ),
    ]
