# Generated by Django 2.2.4 on 2020-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200413_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='company website'),
        ),
    ]
