# Generated by Django 2.2.4 on 2020-05-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200518_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendations',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Recommendations'},
        ),
    ]
